//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models.BD_REVISTAS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_REVISTASEntities : DbContext
    {
        public BD_REVISTASEntities()
            : base("name=BD_REVISTASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USR_PaginaSitioWeb> USR_PaginaSitioWeb { get; set; }
        public virtual DbSet<USR_PermisoSitioWeb> USR_PermisoSitioWeb { get; set; }
    }
}
