//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plantilla.Models.BD_REVISTAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_PermisoSitioWeb
    {
        public int IdPaginaSitioWeb { get; set; }
        public string Usuario { get; set; }
    
        public virtual USR_PaginaSitioWeb USR_PaginaSitioWeb { get; set; }
    }
}
